### PR TITLE
Get correct return items from Recipes

### PR DESCRIPTION
**Pull request by GenDeathrow**
Make sure crafter is returning the correct recipes based on the Recipe.

### CODE REVIEW

**Comment by GenDeathrow** [comment]
Make sure you review it, just so I didn't break anything.

**Comment by EwyBoy** [comment]
Thank you! The code looks good

**Comment by EwyBoy** [comment]
Will be shiped with build EngineersWorkshop-1.0.7-1.10.2, right over Christmas!

**Comment by GenDeathrow** [comment]
Alright glad I was able to help.

**Pull request merged**
