### PR TITLE
Update EngineersWorkshop.java

### PR DESCRIPTION
**Pull request by dries007**
How about we don't crash the server?

### CODE REVIEW

**Comment by JorVaCoding** [comment]
already fixed, didn't push to git though, was getting to curseforge asap, thank you though ❤️

**Comment by dries007** [comment]
Alright :+1:

**Comment by Darkosto** [comment]
When do I get my personal copy that has the same version number so I can login onto servers again?

**Comment by dries007** [comment]
Clay already put this on the sub server, but here you go: https://dl.dries007.net/EngineersWorkshop-1.1.2-1.10.2.jar (This file got ninja fixed just now, if this message wasn't here when you downloaded, redownload)

**Comment by Darkosto** [comment]
Dries pls

**Comment by Darkosto** [comment]
I'd also like to put it on record that if I do indeed have an aneurysm today, I'll be sending a bill to the Engineer's Workshop mod development team.

**Comment by dries007** [comment]
I downloaded there code instead of mine :hankey: 
Its ninja fixed now

**Comment by JorVaCoding** [comment]
@Darkosto A version for you is building, I'll put it on dropbox and put a link here for you.

**Comment by JorVaCoding** [comment]
https://www.dropbox.com/s/9oig64rn36fzd7f/EngineersWorkshop-Darkosto-1.1.2-1.10.2.jar?dl=1

**Pull request closed without merging**
